import pyautogui
import pandas as pd
import time
tabela = pd.read_csv(r"C:\Users\PC\Desktop\ABR REAL tratado.csv") 
pyautogui.PAUSE = 0.40

for linha in tabela.index:
	time.sleep(2.5)
	pyautogui.click(x=12, y=63)
	time.sleep(0.60)
	pyautogui.write('21609217000173')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('1')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('4')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('3')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('3')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('4')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('3')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.hotkey('shift')
	time.sleep(0.60)
	pyautogui.press('backspace')
	time.sleep(0.60)
	pyautogui.write('MEDICALMAIS SERVICOS EM SAUDE LTDA')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('p')
	time.sleep(0.60)
	pyautogui.press('e')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('6')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('4')
	time.sleep(0.60)
	pyautogui.press('1')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('6')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('5')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	valor = tabela.loc[linha, "CNPJ"]
	pyautogui.write(str(tabela.loc[linha, "CNPJ"]))
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(1)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('1')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('1')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('1')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('tab')
	time.sleep(0.60)
	pyautogui.press('enter') 
	time.sleep(5)	
	pyautogui.click(x=682, y=389)
	time.sleep(4)
	
	pyautogui.click(x=71, y=62)
	time.sleep(0.65)
	pyautogui.click(x=323, y=336)
	time.sleep(0.60)	 
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)  # Até aqui ele abriu a escrituração
		#######FASE 2###########
		# 120 efd bloco	
	pyautogui.click(88, 119)
	time.sleep(0.60)
	pyautogui.click(112, 133)
	time.sleep(0.60)
	pyautogui.click(x=129, y=205)
	time.sleep(2)
	pyautogui.click(304, 261) # +
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('4')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('2')
	time.sleep(0.60)
	pyautogui.press('3') #data
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('4') #fixo
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.click(x=640, y=454)
	time.sleep(1)
	# regsitro 0900
	pyautogui.click(x=135, y=259)
	pyautogui.click(x=303, y=263)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.click(x=638, y=602)

	# M200 ; M600
	pyautogui.click(137, 296)
	time.sleep(0.60)
	pyautogui.click(148, 311)
	time.sleep(0.60)
	pyautogui.click(304, 261) # +
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('enter')
	pyautogui.click(637, 574) #save
	time.sleep(0.60)
	pyautogui.click(129, 382)
	time.sleep(0.60)
	pyautogui.click(157, 402)
	time.sleep(0.60)
	pyautogui.click(304, 261) # +
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	time.sleep(0.60)
	pyautogui.press('0')
	time.sleep(0.60)
	pyautogui.press('enter')
	pyautogui.click(643, 573) # save
	time.sleep(4)
	pyautogui.click(141, 57)
	time.sleep(7)
	pyautogui.click(681, 391)
	time.sleep(3)
	pyautogui.click(682, 390)
	time.sleep(2)
	pyautogui.click(227, 63)
	time.sleep(2)

	#FASE 3.5 ############# Gerar Arquivo
	pyautogui.click(164, 55)
	time.sleep(1)
	pyautogui.click(617, 337)
	time.sleep(1)
	pyautogui.click(690, 528)
	time.sleep(1)
	pyautogui.press('enter')
	time.sleep(1)
	pyautogui.click(x=682, y=394)
	time.sleep(5)
	
	###### Assinatura
	time.sleep(3)
	pyautogui.click(x=259, y=64)
	time.sleep(3)
	pyautogui.click(x=358, y=332)
	time.sleep(3)
	pyautogui.click(x=690, y=531)
	time.sleep(3)
	pyautogui.click(x=546, y=320)
	time.sleep(3)
	pyautogui.click(x=873, y=471)
	time.sleep(3)
	pyautogui.click(x=681, y=389)

	##### Transmissão
	time.sleep(3)
	pyautogui.click(x=319, y=67)
	time.sleep(3)
	pyautogui.click(x=482, y=334)
	time.sleep(5)
	pyautogui.click(x=685, y=530)
	time.sleep(3)
	pyautogui.click(x=728, y=429) # nao salvar recibo
	time.sleep(3)


############ exclusão

	time.sleep(2)
	pyautogui.click(x=372, y=64)
	time.sleep(1)
	pyautogui.click(x=474, y=336)
	time.sleep(0.80)
	pyautogui.click(684, 529)
	time.sleep(0.80)
	pyautogui.click(641, 391)
	time.sleep(0.80)
	pyautogui.click(683, 385)
	time.sleep(5)

	